"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { AnalysisReport } from "@/lib/report-types";


export function ReportMethodology({ report }: { report: AnalysisReport }) {
  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Deterministic vs interpretive split</CardTitle>
          <CardDescription>
            What was computed in Python, what an LLM produced, and what was rejected.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 text-sm leading-relaxed text-[color:var(--color-muted)]">
          <p>
            <span className="font-medium text-[color:var(--color-fg)]">Python (deterministic).</span>{" "}
            CSV parsing &amp; validation, ZigZag pivot detection, swing labelling
            (HH/HL/LH/LL), parallel channel fits, Fibonacci retracements / extensions,
            ATR &amp; realized volatility, structural phase hints, and every numeric
            invalidation level shown on this report.
          </p>
          <p>
            <span className="font-medium text-[color:var(--color-fg)]">LLM (Haiku, per timeframe).</span>{" "}
            Proposed up to 3 ranked Elliott Wave candidate counts and 3 NEOWave
            candidate identifications per timeframe, on a compact ~80&ndash;150-token
            structural summary. The LLM never saw raw OHLCV.
          </p>
          <p>
            <span className="font-medium text-[color:var(--color-fg)]">Validator (deterministic Python).</span>{" "}
            Ran 7 hard Elliott rules and 3 hard NEOWave rules against every proposed
            count. Rule-violating counts were rejected before reaching this report.
            Surviving counts received a heuristic-compliance score on top.
          </p>
          <p>
            <span className="font-medium text-[color:var(--color-fg)]">LLM (Sonnet, single call).</span>{" "}
            Cross-timeframe + cross-framework synthesis: identifies alignment
            between timeframes, agreement / disagreement between Elliott and
            NEOWave, and ranks the top 3 overall scenarios. Numeric invalidation
            prices are NOT generated by Sonnet — they are looked up from the
            Validator&apos;s output for each supporting count.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Cost breakdown</CardTitle>
          <CardDescription>
            Total spend for this run: ${report.total_cost_usd.toFixed(6)} USD.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <table className="w-full text-xs">
            <thead className="text-[color:var(--color-muted)]">
              <tr className="border-b border-[color:var(--color-border)]">
                <th className="py-2 text-left font-medium">Agent</th>
                <th className="py-2 text-left font-medium">Model</th>
                <th className="py-2 text-right font-medium">Input</th>
                <th className="py-2 text-right font-medium">Output</th>
                <th className="py-2 text-right font-medium">Cost (USD)</th>
                <th className="py-2 text-right font-medium">Cache</th>
              </tr>
            </thead>
            <tbody className="font-mono text-[color:var(--color-fg)]">
              {report.cost_breakdown.map((c, i) => (
                <tr key={i} className="border-b border-[color:var(--color-border)]/40">
                  <td className="py-1.5">{c.agent_name}</td>
                  <td className="py-1.5">{c.model}</td>
                  <td className="py-1.5 text-right">{c.input_tokens}</td>
                  <td className="py-1.5 text-right">{c.output_tokens}</td>
                  <td className="py-1.5 text-right">{c.cost_usd.toFixed(6)}</td>
                  <td className="py-1.5 text-right text-[color:var(--color-muted)]">
                    {c.cache_hit ? "hit" : "miss"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Encoded rules</CardTitle>
          <CardDescription>
            Hard Elliott rules: EW-H-1 .. EW-H-7. Hard NEOWave rules: NW-H-1, NW-H-2,
            NW-H-4. Heuristics (soft): EW-S-1, EW-S-2. The full list with citations
            lives in <code>ELLIOTT_RULES.md</code> at the project root.
          </CardDescription>
        </CardHeader>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>What this is not</CardTitle>
          <CardDescription>
            This report does not predict price, signal entries / exits, or estimate
            probabilities of future moves. Every number is a property of past
            geometry. Decisions belong to the human reading the report.
          </CardDescription>
        </CardHeader>
      </Card>
    </div>
  );
}
